# Generated by Django 5.2.8 on 2026-01-04 16:50

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
