# Generated by Django 5.2.8 on 2025-11-20 16:53

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, help_text='You can change the question above. IMPORTANT: This answer will be required to reset your password.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, help_text='You can change the question above. IMPORTANT: This answer will be required to reset your password.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, choices=[('nick_name', 'What is your nick name?'), ('first_pet', 'What was the name of your first pet?'), ('first_school', 'What was the name of your first school?'), ('favorite_book', 'What is your favorite book?'), ('birth_city', 'In what city were you born?')], default=users.models.get_random_question, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, choices=[('nick_name', 'What is your nick name?'), ('first_pet', 'What was the name of your first pet?'), ('first_school', 'What was the name of your first school?'), ('favorite_book', 'What is your favorite book?'), ('birth_city', 'In what city were you born?')], default=users.models.get_random_question, max_length=50),
        ),
    ]
